rules:
  property-sort-order: 0
  class-name-format: 0
  leading-zero: 0
  no-color-literals: 0
  mixins-before-declarations: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  force-attribute-nesting: 0
  pseudo-element: 0
  shorthand-values: 0
  border-zero: 0
  url-quotes: 0
  no-trailing-zero: 0
  no-css-comments: 0
  nesting-depth:
    - 1
    -
      max-depth: 3
  no-vendor-prefixes:
    - 1
    -
      ignore-non-standard: true
